import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [
    {
      type: 'category',
      label: 'About the Author',
      items: ['ghulam-sarwar-khan-biography'],
    },
    {
      type: 'category',
      label: 'Book Chapters',
      items: [
        'chapters/chapter-1-intro',
        'chapters/chapter-2-clarify-values',
        'chapters/chapter-3-audit',
        'chapters/chapter-4-ideation',
        'chapters/chapter-5-prototyping',
        'chapters/chapter-6-habits',
        'chapters/chapter-7-decision-frameworks',
        'chapters/chapter-8-portfolio',
        'chapters/chapter-9-ethics',
        'chapters/chapter-10-ship',
        'glossary',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial-basics', // assuming tutorial-basics is a subdirectory with existing tutorials
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial-extras', // assuming tutorial-extras is a subdirectory with existing tutorials
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
